baseURL = "https://aitextmagic.com"
languageCode = "en-us"
title = "AITextMagic - AI-Powered Text Generation"
enableRobotsTXT = true

pagination.pagerSize  = 5

[outputs]
  home = ["HTML", "RSS", "SITEMAP"]

[params]
  author = "AITextMagic Team"
  description = "Free AI-powered tools for summarizing text, performing text sentiment analysis, and converting text to speech."
  keywords = "summarize text generator, text sentiment analysis, convert text to speech free, AI text tools, free text summarizer, speech synthesis"
  email = ""
  phone = ""
  address = ""
  
  # Social links
  facebook = ""
  twitter = ""
  linkedin = ""
  github = ""

# Main menu
[[menus.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menus.main]]
  name = "About"
  url = "/about/"
  weight = 20

[[menus.main]]
  name = "Blog"
  url = "/blog/"
  weight = 30

[[menus.main]]
  name = "Privacy Policy"
  url = "/privacy-policy/"
  weight = 40

